apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: root-project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.7.2
    chart: kube-prometheus-stack
destination:
  server: https://kubernetes.default.svc
  namespace: prometheus
syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true