apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: root-project
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 51.3.0
    chart: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated: 
      prune: true
      selfHeal: true